package config;

import io.appium.java_client.AppiumDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.support.ui.WebDriverWait;

public class setUp {

    protected static AppiumDriver driver;
    protected static DesiredCapabilities desiredCapabilities;
    protected static WebDriverWait wait;

//Time duration
    protected static int duration = 60;
    protected static int threadSleep = 3000;
    protected static int threadSleepOpeningApplication = 5000;


//Device Setting
    protected static String[] device = {"redmi", "emulator", "vivo", "oppo"};
    protected static String devicesUsed = device[3];

//Variable

    protected static String companyName = "Generated by Java Appium";
    protected static String teamName = "Team generated by Java Appium";
    protected static String listName1 = "List 1 by Java Appium";
    protected static String listName2 = "List 2 by Java Appium";
    protected static String cardName1 = "Card 1 Auto";
    protected static String cardNameEdit = cardName1+" New";
    protected static String cardName2 = "Card 2 Auto";

    protected static String description = "Description generated by Java Appium";
    protected static String userName = "Made Rasti";

    protected static String textCheers = "Cheers!";

    protected static String labelName = "label appium";
    //List Assertion

    protected static String initialListInPlaceA;

    protected static String initialListInPlaceB;

    protected static int initialCardAmount;

}
